### Get array of all articles
# Article: {
#   id:string, 
#   title:string, 
#   url: string
# }
GET https://x03xdh6x33.execute-api.us-east-1.amazonaws.com/dev/articles


### Get article by id 
# Article: {
#   id: string, 
#   slug: string, 
#   title: string,
#   meta_title: string, 
#   meta_description: string, 
#   content: string, 
#   created_at: number, 
#   updated_at: number,
#   file_id: string,
#   url: string 
# }
GET https://x03xdh6x33.execute-api.us-east-1.amazonaws.com/dev/articles/:id

### Post new article
### All properties in request body required
# encodedString = base64(login:password)
POST https://x03xdh6x33.execute-api.us-east-1.amazonaws.com/dev/articles/create
Authorization: Basic <encodedString>
Content-Type: application/json

{
    "title": "asdfdfd",
    "meta_title": "qwevhgfxrty212458",
    "meta_description": "metacsdvaqweqwrty322222",
    "content": "contentqweadfhsfbvsdfdnty311121",
    "file_id": "d9bdbf96-b972-4692-a160-4c0fa9158a3c"
}

### Change article by id
# Properties in body is optional, but at least one required
# encodedString = base64(login:password)

PUT https://x03xdh6x33.execute-api.us-east-1.amazonaws.com/dev/articles/:id
Authorization: Basic YWRtaW46cXdlcnR5MTIz
Content-Type: application/json

{
    "title": "abcdsafsgfsdgdsefghigklmnop",
    "meta_title": "qwerty228",
    "meta_description": "metaqwerty322",
    "content": "contentqweadsfbdnty321"
}

### Get pre-sign url for upload images with fields
### NOTE: If need rewrite image by existing key - set it in query params as fileId = key
# {
#     "url": "https://s3.amazonaws.com/blog-api-dev-image-bucket",   *** URL of POST request for uploading image
#     "fields": {                                                    *** This fields generated by API and required in POST request form-data body
#         "acl": string,
#         "key": string,                                             *** key === file_id => required for creating new article (check POST endpoint)
#         "bucket": string,
#         "X-Amz-Algorithm": string,
#         "X-Amz-Credential": string,
#         "X-Amz-Date": string,
#         "X-Amz-Security-Token": string,
#         "Policy": string,
#         "X-Amz-Signature": string
#     }
# }
GET https://x03xdh6x33.execute-api.us-east-1.amazonaws.com/dev/getPresignUrl